server:
  port: ${PORT:31001}

spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri:  mongodb://localhost:27017/xc_cms
      database: xc_cms
  freemarker:
    cache: false # 关闭缓存,方便测试
    settings:
      template_update_delay: 0 # 检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /

eureka:
  client:
    registerWithEureka: true # 服务注册，是否将自己注册到Eureka服务中,高可用需要使用，相互注册
    fetchRegistry: true # 服务发现，是否从Eureka中获取注册信息
    serviceUrl: # Eureka 客户端与Eureka服务端的交互地址,多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://eureka01:50101/eureka/,http://eureka02:50102/eureka/} # 高可用环境下需要使用域名,注册到其他服务器
  instance:
    prefer-ip-address: true # 将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} # 指定实例id